### 📗 GET List user

GET http://localhost:9191/saas/api/user/
Authorization: Bearer {{auth_token}}

### 📗 GET Single user

GET http://localhost:9191/saas/api/user/05868f49-e28c-49de-bc33-df21e5251269
Authorization: Bearer {{auth_token}}

### 💛 POST Save user

POST http://localhost:9191/saas/api/user/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user18",
  "password": "user",
  "fullName": "Usuario",
  "enabled": true
}

### 🔵 PUT Update Customer contact

PUT http://localhost:9191/saas/api/user/05868f49-e28c-49de-bc33-df21e5251269
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user15",
  "password": "user",
  "fullName": "User Updated",
  "enabled": false
}


### 🏮 DELETE Delete user

DELETE http://localhost:9191/saas/api/user/ffd7c6cc-c8e7-4ceb-a14d-dee93c57dba8
Authorization: Bearer {{auth_token}}


###


