### 📗 GET List user

GET http://localhost:9191/saas/api/user/


### 📗 GET Single user

GET http://localhost:9191/saas/api/user/1
Accept: application/json

### 💛 POST Save user

POST http://localhost:9191/saas/api/user/
Content-Type: application/json

{
    "username": "test 3",
    "password": "test",
    "fullName": "Usuario test 3",
    "enabled": 1
}

### 🔵 PUT Update Customer contact

PUT http://localhost:9191/saas/api/user/2
Content-Type: application/json

{
  "username": "test 2 nuevo",
  "password": "test1234",
  "fullName": "Usuario test 2 updated",
  "enabled": 0
}


### 🏮 DELETE Delete user

DELETE http://localhost:9191/saas/api/user/5
Content-Type: application/x-www-form-urlencod


###


