### 📗 GET List customer

GET http://localhost:9191/saas/api/customer
Authorization: Bearer {{auth_token}}

### 📗 GET Single customer

GET http://localhost:9191/saas/api/customer/2d2fb97e-ecda-4a98-80f0-1a1584d81eb4
Authorization: Bearer {{auth_token}}
Accept: application/json

### 🔵 PUT Update Customer

PUT http://localhost:9191/saas/api/customer/2d2fb97e-ecda-4a98-80f0-1a1584d81eb4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "documentNumber" : "20564379248",
  "name": "FASTWORKX S.R.L.",
  "address": "AV. ARGENTINA NRO. 146 (A 1 CDRA MUNICIPALIDAD LAS AMERICAS) APURIMAC - ABANCAY - ABANCAY",
  "email": "puyu.com.pe",
  "phone": "978189845"
}

### 🏮 DELETE Delete customer

DELETE http://localhost:9191/saas/api/customer/2d2fb97e-ecda-4a98-80f0-1a1584d81eb4
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencod

### 💛 POST Save customer

POST http://localhost:9191/saas/api/customer/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "documentNumber" : "20564379248",
  "name": "FASTWORKX S.R.L. 10",
  "address": "AV. ARGENTINA NRO. 146 (A 1 CDRA MUNICIPALIDAD LAS AMERICAS) APURIMAC - ABANCAY - ABANCAY",
  "email": "puyu.com.pe",
  "phone": "979845"
}

###


