### 📗 GET Get all contact

GET http://localhost:9191/saas/api/contact
Authorization: Bearer {{auth_token}}

### 📗 GET Single contact

GET http://localhost:9191/saas/api/contact/01393d38-c86e-4dc3-a65a-832603f98b73
Authorization: Bearer {{auth_token}}
Accept: application/json

### 💛 POST Save contact

POST http://localhost:9191/saas/api/contact/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Nuevo",
  "lastName": "Contacto",
  "phone": "984786712",
  "jobTitle": "Vendedor"
}

### 🔵 PUT Update Customer contact

PUT http://localhost:9191/saas/api/contact/01393d38-c86e-4dc3-a65a-832603f98b73
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Updated",
  "lastName": "Contacto 2",
  "phone": "982123243",
  "jobTitle": "Gerente"
}

### 🏮 DELETE Delete contact

DELETE http://localhost:9191/saas/api/contact/01393d38-c86e-4dc3-a65a-832603f98b73
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencod

###

