# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false


    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # path to validations
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/src/Infrastructure/Framework/Validation/"

    # Path to serializer
    serializer:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/src/Infrastructure/Framework/Serializer'

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
