### 📗 GET List customer

GET http://localhost:9191/saas/api/customer
Authorization: Bearer {{auth_token}}

### 4e88c291-a678-4030-9890-759b29e68d0b

### 📗 GET All products

GET http://localhost:9191/saas/api/product
Authorization: Bearer {{auth_token}}

### f6cf0fb1-d386-4b6e-9c1e-3714dab73e51

### ##################################################################33
### 📗 GET All projects

GET http://localhost:9191/saas/api/project
Authorization: Bearer {{auth_token}}

### 📗 GET Single project

GET http://localhost:9191/saas/api/project/7a8ddee4-4272-48d9-b7e4-7ef33e2cf915
Authorization: Bearer {{auth_token}}
Accept: application/json

### 💛 POST Save project

POST http://localhost:9191/saas/api/project/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "customerId": "72cd2eb5-b572-421f-90af-13895c0f67fe",
  "productId": "f6cf0fb1-d386-4b6e-9c1e-3714dab73e51"
}


### 🔵 PUT Update project

PUT http://localhost:9191/saas/api/project/b48ce9b0-28f5-4990-bfca-e16f7e9e2e6b
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "customerId": "72cd2eb5-b572-421f-90af-13895c0f67fe",
  "productId": "aca2ab97-a26b-45ab-9af9-24ea8af6603a"
}

### 🏮 DELETE Delete project

DELETE http://localhost:9191/saas/api/project/b48ce9b0-28f5-4990-bfca-e16f7e9e2e6b
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencod

###


