imports:
    - { resource: Packages/saas_project_doctrine.yaml }
    - { resource: Packages/saas_project_framework.yaml }

when@prod:
when@dev:
    services:
        App\Saas\Project\Infrastructure\Persistence\Doctrine\Repository\DoctrineProjectRepository: ~
        App\Saas\Project\Domain\Repository\ProjectRepository: '@App\Saas\Project\Infrastructure\Persistence\Doctrine\Repository\DoctrineProjectRepository'