### 📗 GET All products

GET http://localhost:9191/saas/api/product
Authorization: Bearer {{auth_token}}

### 📗 GET Single product

GET http://localhost:9191/saas/api/product/3416659a-1857-449e-b001-ce26a732571d
Authorization: Bearer {{auth_token}}
Accept: application/json

### 💛 POST Save product

POST http://localhost:9191/saas/api/product/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "code": "YUB",
  "name": "Yubiz",
  "description": "Sistema para micro y mediana empresas.",
  "url": "yubiz.puyu.pe",
  "image": "yubiz/img/static.jpg"
}


### 🔵 PUT Update product

PUT http://localhost:9191/saas/api/product/521a0392-0d96-454d-89ec-c34d10763be5
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "code": "YuBiz New code",
  "name": "Yubiz edit",
  "description": "Sistema para micro y mediana empresas.",
  "url": "yubiz.puyu.pe",
  "image": "yubiz/img/static.jpg"
}

### 🏮 DELETE Delete product

DELETE http://localhost:9191/saas/api/product/548c1383-889d-4b0e-b610-23a496190366
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencod

###


