imports:
    - { resource: Packages/saas_user_doctrine.yaml }
    - { resource: Packages/saas_user_framework.yaml }

services:
    App\Saas\User\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository: ~
    App\Saas\User\Domain\UserRepository: '@App\Saas\User\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository'