App\Saas\Project\Domain\Project:
    type: entity
    repositoryClass: App\Saas\Project\Domain\Repository\ProjectRepository
    table: project
    id:
        id:
            type: uuid
            length: 16
            unique: true
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    manyToOne:
        customer:
            targetEntity: App\Saas\Customer\Domain\Customer
            fetch: LAZY
            joinColumn:
                nullable: false
        product:
            targetEntity: App\Saas\Product\Domain\Product
            fetch: LAZY
            joinColumn:
                nullable: false