App\Saas\Project\Application\Create\CreateProjectDto:
  properties:
    customerId:
      - NotBlank: ~
    productId:
      - NotBlank: ~
    key:
      - NotBlank: ~
    startDate:
      - NotBlank: ~
    logo:
      - NotBlank: ~
    color:
      - NotBlank: ~
    configData:
      - NotBlank: ~
    suspended:
      - NotBlank: ~
    description:
      - Blank: ~
    observation:
      - Blank: ~