App\Saas\User\Domain\Entity\User:
    type: entity
    repositoryClass: App\Saas\User\Domain\Repository\UserRepository
    table: customer_contact
    id:
        id:
            type: uuid
            unique: true
    fields:
        username:
            type: string
            length: 100
        password:
            type: string
            length: 100
        fullName:
            type: string
            length: 250
        enabled:
            type: integer