App\Saas\User\Domain\User:
    type: entity
    repositoryClass: App\Saas\User\Domain\UserRepository
    table: user
    id:
        id:
            type: uuid
            length: 16
            unique: true
    fields:
        username:
            type: string
            length: 100
        password:
            type: string
            length: 100
        fullName:
            type: string
            length: 250
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false