#controllers:
#    resource: ../src/CustomerContact/Infrastructure/Ui/Controller/
#    type: attribute
saas_directory:
    resource: ../src/Saas/Shared/Infrastructure/Config/Routes/
    type: directory
auth_directory:
    resource: ../src/Auth/User/Infrastructure/Config/Routes/
    type: directory