# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.jttp_handler:
        class: App\Infrastructure\Api\Handlers\JttpHandler
        arguments:
            - "@logger"

    app.view_handler:
        parent: fos_rest.view_handler.default
        autowire: false
        autoconfigure: false
        public: false
        calls:
            - [ 'registerHandler', [ 'json', [ "@app.jttp_handler", 'createResponse' ] ] ]

    App\Infrastructure\Shared\Validation\Validator: ~
    App\Domain\Shared\Validator: '@App\Infrastructure\Shared\Validation\Validator'

    App\Infrastructure\Notifier\SlackNotifier: ~
    App\Domain\Notification\Notifier: '@App\Infrastructure\Notifier\SlackNotifier'

    App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCustomerContactRepository: ~
    App\Domain\Repository\CustomerContactRepository: '@App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCustomerContactRepository'