services:
    app.jttp_handler:
        class: App\Saas\Shared\Infrastructure\Api\Handlers\JttpHandler
        arguments:
            - "@logger"

    app.view_handler:
        parent: fos_rest.view_handler.default
        autowire: false
        autoconfigure: false
        public: false
        calls:
            - [ 'registerHandler', [ 'json', [ "@app.jttp_handler", 'createResponse' ] ] ]

    App\Saas\Shared\Infrastructure\Validation\Validator: ~
    App\Saas\Shared\Domain\Validation\Validator: '@App\Saas\Shared\Infrastructure\Validation\Validator'

    App\Saas\Shared\Infrastructure\Notifier\SlackNotifier: ~
    App\Saas\Shared\Domain\Notification\Notifier: '@App\Saas\Shared\Infrastructure\Notifier\SlackNotifier'

imports:
    - { resource: ../../../CustomerContact/Infrastructure/Config/saas_customer_contact_service.yaml }