services:
    app.jttp_handler:
        class: App\Saas\Shared\Infrastructure\Api\Handlers\JttpHandler
        arguments:
            - "@logger"

    app.view_handler:
        parent: fos_rest.view_handler.default
        autowire: false
        autoconfigure: false
        public: false
        calls:
            - [ 'registerHandler', [ 'json', [ "@app.jttp_handler", 'createResponse' ] ] ]

    App\Saas\Shared\Infrastructure\Validation\SymfonyValidator: ~
    App\Saas\Shared\Domain\Validation\Validator: '@App\Saas\Shared\Infrastructure\Validation\SymfonyValidator'

    App\Saas\Shared\Infrastructure\Notifier\SlackNotifier: ~
    App\Saas\Shared\Domain\Notification\Notifier: '@App\Saas\Shared\Infrastructure\Notifier\SlackNotifier'

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
imports:
    - { resource: Services/ }
    - { resource: Packages/ }
