imports:
    - { resource: Packages/saas_product_doctrine.yaml }
    - { resource: Packages/saas_product_framework.yaml }

when@prod:
when@dev:
    services:
        App\Saas\CustomerContact\Infrastructure\Persistence\Doctrine\Repository\DoctrineCustomerContactRepository: ~
        App\Saas\CustomerContact\Domain\Repository\CustomerContactRepository: '@App\Saas\CustomerContact\Infrastructure\Persistence\Doctrine\Repository\DoctrineProductRepository'

when@test:
    services:
        App\Saas\CustomerContact\Infrastructure\Persistence\InMemory\InMemoryCustomerContactRepository: ~
        App\Saas\CustomerContact\Domain\Repository\CustomerContactRepository: '@App\Saas\CustomerContact\Infrastructure\Persistence\InMemory\InMemoryProductRepository'