App\Saas\Product\Application\Create\CreateProductDto:
  properties:
    code:
      - NotBlank: ~
      - Length:
          max: 20
          minMessage: 'El codigo tiene que tener una longitud maxima de {{ limit }}'
    name:
      - NotBlank: ~
    url:
      - NotBlank: ~
