App\Saas\Customer\Domain\Customer:
    type: entity
    repositoryClass: App\Saas\Customer\Domain\Repository\CustomerRepository
    table: customer
    id:
        id:
            type: uuid
            length: 16
            unique: true
    fields:
        documentNumber:
            type: string
            length: 11
        name:
            type: string
            length: 200
        address:
            type: string
            length: 150
        email:
            type: string
            length: 40
        phone:
            type: string
            length: 20
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false