imports:
    - { resource: Packages/saas_directory_doctrine.yaml }
    - { resource: Packages/saas_directory_framework.yaml }

when@prod:
when@dev:
    services:
        App\Saas\Directory\Infrastructure\Persistence\Doctrine\Repository\DoctrineDirectoryRepository: ~
        App\Saas\Directory\Domain\Repository\DirectoryRepository: '@App\Saas\Directory\Infrastructure\Persistence\Doctrine\Repository\DoctrineDirectoryRepository'